### ISSUE TITLE
Do not use `+` between scopes

### ISSUE THREAD

**Issue by jasonkuhrt** [jasonkuhrt/oauth2-implicit#17]
Or make it configurable. It appears that `+` does not work in newer versions of Doorkeeper (https://github.com/littlebitselectronics/little_bits/issues/1516#issuecomment-68164036)

**Comment by jasonkuhrt** [comment]
@stresslimit @hecbuma throw me a bone here. Status?

**Comment by stresslimit** [comment]
@jasonkuhrt @hecbuma I don't know, but I think "+" is like a standard thing, meaning either there is something wrong with doorkeeper or something else is causing this error. In any case I think we should support "+"-separated, rather than changing `jasonkuhrt/oauth2-implicit`.

Or, the + is really about URIEncoding; when we `curl` is gives an actual + character which is escaped so won't be re-parsed as space? Just wondering... in any case we will be moving away from `jasonkuhrt/oauth2-implicit` towards password flow, but should figure this out.

**Comment by hecbuma** [comment]
I checked and I found deep in doorkeeper this line https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/oauth/scopes.rb#L10 basically it split the string by spaces and since "admin+write+read" it's one string it return a 401  with this message:

```
    "error": "invalid_scope",
    "error_description": "The requested scope is invalid, unknown, or malformed."
```

I don't why this used to worked  'cause looks like that code has been all the time.

**Comment by jasonkuhrt** [comment]
Thanks a lot guys, with this additional info I'll more closely at how my lib can work right.

**Comment by stresslimit** [comment]
@hecbuma Check the example URL https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Scopes#requesting-particular-scopes 

It has scopes separated with + `&scope=public+write`

**Comment by hecbuma** [comment]
hmm that's weird or wrong 'cause when debug here https://github.com/doorkeeper-gem/doorkeeper/blob/v2.0.0/lib/doorkeeper/oauth/helpers/scope_checker.rb#L10
I found the following:

```
> server_scopes
=> #<Doorkeeper::OAuth::Scopes:0x007fccb646ae58
 @scopes=["read", "write", "admin", "ifttt"]>
```

and then 
```
> OAuth::Scopes.from_string(scope)
=> #<Doorkeeper::OAuth::Scopes:0x007fccb9a58768 @scopes=["admin+write+read"]>
```

As you can see it cannot match the scopes when it has `+` on it

**Comment by stresslimit** [comment]
Yeah I think something's wrong, "+" is a really common url-encoding for like searches [eg `somesite.com/search?q=search+terms`] and since it worked before I think we have a routing or param-parsing issue

**Comment by jasonkuhrt** [comment]
Closing until clearer data is available.

**Comment by jasonkuhrt** [comment]
As specified here `scope` must be space delimited http://tools.ietf.org/html/rfc6749#section-3.3. As claimed here Doorkeeper is spec compliant with https://github.com/doorkeeper-gem/doorkeeper/wiki/Supported-Features v22 of the OAuth2 spec which specifies the same thing.
